export { default as Button } from './Button'
export { default as IconButton } from './IconButton'
export { default as LearnImg1 } from './LearnImg1'
export { default as LearnImg2 } from './LearnImg2'
export { default as PlatformCard1 } from './PlatformCard1'
export { default as PlatformCard2 } from './PlatformCard2'
export { default as PlatformCard3 } from './PlatformCard3'